# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'AquaTerra' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AquaTerra
  pod 'Amplify'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
  pod 'SwiftUI-SimpleToast', :git => 'https://github.com/sanzaru/SimpleToast.git'

end
